// Generated by CoffeeScript 1.8.0
(function() {
  var IndexController;

  angular.module('threeJsBlobApp').controller('IndexController', IndexController = (function() {
    function IndexController() {
      this.geometry_types = ['Cube'];
    }

    return IndexController;

  })());

}).call(this);
