// Generated by CoffeeScript 1.8.0
(function() {
  angular.module('threeJsBlobApp').directive('renderer', function(renderService) {
    return {
      restrict: 'E',
      link: function(scope, elem, attrs) {
        var renderer_elem;
        renderer_elem = renderService.set_parent_elem($(elem[0]).parent());
        elem.append(renderer_elem);
        renderService.start_render();
        return scope.$on('$destroy', function() {
          return renderService.cancel_render();
        });
      }
    };
  });

}).call(this);
