// Generated by CoffeeScript 1.8.0
(function() {
  angular.module('threeJsBlobApp').directive('renderer', function() {
    return {
      restrict: 'E',
      link: function(scope, elem, attrs) {
        var animate, camera, init, on_resize, render, renderer, scene;
        camera = null;
        scene = null;
        renderer = null;
        on_resize = function() {
          var height, width;
          width = $(elem).parent().width() - 10;
          height = $(elem).parent().height() - 10;
          renderer.setSize(width, height);
          camera.aspect = width / height;
          return camera.updateProjectionMatrix();
        };
        init = function() {
          var height, width;
          width = $(elem).parent().width() - 10;
          height = $(elem).parent().height() - 10;
          camera = new THREE.PerspectiveCamera(50, width / height, 1, 2000);
          camera.position.set(0, 0, 1);
          scene = new THREE.Scene();
          scene.add(new THREE.AmbientLight(0x000000));
          renderer = new THREE.WebGLRenderer();
          renderer.setSize(width, height);
          elem[0].appendChild(renderer.domElement);
          return window.addEventListener('resize', on_resize, false);
        };
        render = function() {
          return renderer.render(scene, camera);
        };
        animate = function() {
          requestAnimationFrame(animate);
          return render();
        };
        init();
        return animate();
      }
    };
  });

}).call(this);
